pipeline{
    agent none
    stages {
        stage('something else'){
            agent any

            steps {
                sh 'ls'
            }
        }
        stage('infrastructure') {
            agent {
                dockerfile {
                    dir 'application-one'
                }
            }
            steps {
                sh 'python --version'
                sh 'ls -l'



            }
        }
    }
}