node {
    checkout scm

    def infraImage

    stage('build image') {
        infraImage = docker.build("test:${env.BUILD_ID}", "application-one")
    }

    customImage.inside {
        sh 'ls'
        sh 'cdk ls'
    }
}