pipeline{
    agent none
    stages {
        stage('something else'){
            agent any

            steps {
                sh 'ls'
            }
        }
        stage('infrastructure') {
            agent {
                dockerfile {
                    dir 'application-one'
                    args '-u root'
                }
            }
            steps {

                sh 'ls'
                sh './application-one ls'
                sh '/app ls'
                sh 'cdk ls'

            }
        }
    }
}